#if defined _mewjam_radio_info_included_
#endinput
#endif
#define _mewjam_radio_info_included_

#include <mewjam/version>

#define MEWJAM_RADIO_NAME "Mewjam/Radio"
#define MEWJAM_RADIO_NAME_LOWER "mewjam_radio"
#define MEWJAM_RADIO_AUTHOR "Mee;w"
#define MEWJAM_RADIO_DESCRIPTION "Modifies & blocks radio messages"
#define MEWJAM_RADIO_URL "https://github.com/kty-trikz/plugins"

#define MEWJAM_RADIO_VERSION_MAJOR 0
#define MEWJAM_RADIO_VERSION_MINOR 1
#define MEWJAM_RADIO_VERSION_PATCH 1

#define MEWJAM_RADIO_VERSION_MAJOR_STRING "0"
#define MEWJAM_RADIO_VERSION_MINOR_STRING "1"
#define MEWJAM_RADIO_VERSION_PATCH_STRING "1"

#define MEWJAM_RADIO_VERSION MEWJAM_VERSION_IMPL(MEWJAM_RADIO_VERSION_MAJOR_STRING, MEWJAM_RADIO_VERSION_MINOR_STRING, MEWJAM_RADIO_VERSION_PATCH_STRING)
