#if defined _mewjam_damage_info_included_
#endinput
#endif
#define _mewjam_damage_info_included_

#include <mewjam/version>

#define MEWJAM_DAMAGE_NAME "Mewjam/Damage"
#define MEWJAM_DAMAGE_NAME_LOWER "mewjam_damage"
#define MEWJAM_DAMAGE_AUTHOR "Mee;w"
#define MEWJAM_DAMAGE_DESCRIPTION "Removes damage by its type"
#define MEWJAM_DAMAGE_URL "https://github.com/kty-trikz/plugins"

#define MEWJAM_DAMAGE_VERSION_MAJOR 0
#define MEWJAM_DAMAGE_VERSION_MINOR 2
#define MEWJAM_DAMAGE_VERSION_PATCH 1

#define MEWJAM_DAMAGE_VERSION_MAJOR_STRING "0"
#define MEWJAM_DAMAGE_VERSION_MINOR_STRING "2"
#define MEWJAM_DAMAGE_VERSION_PATCH_STRING "1"

#define MEWJAM_DAMAGE_VERSION MEWJAM_VERSION_IMPL(MEWJAM_DAMAGE_VERSION_MAJOR_STRING, MEWJAM_DAMAGE_VERSION_MINOR_STRING, MEWJAM_DAMAGE_VERSION_PATCH_STRING)
