#if defined _mewjam_stats_info_included_
#endinput
#endif
#define _mewjam_stats_info_included_

#include <mewjam/version>

#define MEWJAM_STATS_NAME "Mewjam/Stats"
#define MEWJAM_STATS_NAME_LOWER "mewjam_stats"
#define MEWJAM_STATS_AUTHOR "Mee;w"
#define MEWJAM_STATS_DESCRIPTION "Various stats on events"
#define MEWJAM_STATS_URL "https://github.com/kty-trikz/plugins"

#define MEWJAM_STATS_VERSION_MAJOR 0
#define MEWJAM_STATS_VERSION_MINOR 1
#define MEWJAM_STATS_VERSION_PATCH 0

#define MEWJAM_STATS_VERSION_MAJOR_STRING "0"
#define MEWJAM_STATS_VERSION_MINOR_STRING "1"
#define MEWJAM_STATS_VERSION_PATCH_STRING "0"

#define MEWJAM_STATS_VERSION MEWJAM_VERSION_IMPL(MEWJAM_STATS_VERSION_MAJOR_STRING, MEWJAM_STATS_VERSION_MINOR_STRING, MEWJAM_STATS_VERSION_PATCH_STRING)
