"Weapons"
{
    "slot#0"
    {
        "weapon_scout"
        {
            "name" "Scout"
            "slot" "0"
        }

        "weapon_awp"
        {
            "name" "AWP"
            "slot" "0"
        }

        "weapon_m4a1"
        {
            "name" "M4A1"
            "slot" "0"
        }

        "weapon_ak47"
        {
            "name" "AK-47"
            "slot" "0"
        }

        "weapon_famas"
        {
            "name" "Famas"
            "slot" "0"
        }

        "weapon_aug"
        {
            "name" "AUG"
            "slot" "0"
        }

        "weapon_galil"
        {
            "name" "Galil"
            "slot" "0"
        }

        "weapon_sg552"
        {
            "name" "SG-552"
            "slot" "0"
        }

        "weapon_m3"
        {
            "name" "M3"
            "slot" "0"
        }

        "weapon_xm1014"
        {
            "name" "XM-1014"
            "slot" "0"
        }

        "weapon_tmp"
        {
            "name" "TMP"
            "slot" "0"
        }

        "weapon_mac10"
        {
            "name" "MAC-10"
            "slot" "0"
        }

        "weapon_mp5navy"
        {
            "name" "MP5"
            "slot" "0"
        }

        "weapon_ump45"
        {
            "name" "UMP-45"
            "slot" "0"
        }

        "weapon_p90"
        {
            "name" "P90"
            "slot" "0"
        }

        "weapon_g3sg1"
        {
            "name" "G3SG1"
            "slot" "0"
        }

        "weapon_sg550"
        {
            "name" "SG-550"
            "slot" "0"
        }

        "weapon_m249"
        {
            "name" "M249"
            "slot" "0"
        }
    }

    "slot#1"
    {
        "weapon_usp"
        {
            "name" "USP"
            "slot" "1"
        }

        "weapon_glock"
        {
            "name" "Glock"
            "slot" "1"
        }

        "weapon_deagle"
        {
            "name" "Deagle"
            "slot" "1"
        }

        "weapon_p228"
        {
            "name" "P228"
            "slot" "1"
        }

        "weapon_fiveseven"
        {
            "name" "Five-Seven"
            "slot" "1"
        }

        "weapon_elite"
        {
            "name" "Elite"
            "slot" "1"
        }
    }

    "slot#2"
    {
        "weapon_knife"
        {
            "name" "Knife"
            "slot" "2"
        }
    }

    "slot#3"
    {
        "weapon_flashbang"
        {
            "name" "Flashbang"
            "slot" "3"
        }

        "weapon_smokegrenade"
        {
            "name" "Smoke"
            "slot" "3"
        }

        "weapon_hegrenade"
        {
            "name" "HE"
            "slot" "3"
        }
    }
}
