#if defined _mewjam_punch_info_included_
#endinput
#endif
#define _mewjam_punch_info_included_

#include <mewjam/version>

#define MEWJAM_PUNCH_NAME "Mewjam/Punch"
#define MEWJAM_PUNCH_NAME_LOWER "mewjam_punch"
#define MEWJAM_PUNCH_AUTHOR "Mee;w"
#define MEWJAM_PUNCH_DESCRIPTION "Removes player fall view punch"
#define MEWJAM_PUNCH_URL "https://github.com/kty-trikz/plugins"

#define MEWJAM_PUNCH_VERSION_MAJOR 0
#define MEWJAM_PUNCH_VERSION_MINOR 1
#define MEWJAM_PUNCH_VERSION_PATCH 1

#define MEWJAM_PUNCH_VERSION_MAJOR_STRING "0"
#define MEWJAM_PUNCH_VERSION_MINOR_STRING "1"
#define MEWJAM_PUNCH_VERSION_PATCH_STRING "1"

#define MEWJAM_PUNCH_VERSION MEWJAM_VERSION_IMPL(MEWJAM_PUNCH_VERSION_MAJOR_STRING, MEWJAM_PUNCH_VERSION_MINOR_STRING, MEWJAM_PUNCH_VERSION_PATCH_STRING)
