#if defined _mewjam_punch_prop_included_
#endinput
#endif
#define _mewjam_punch_prop_included_

#if defined MEWJAM_PUNCH_VEC_ANGLE
#error `MEWJAM_PUNCH_VEC_ANGLE` is already defined _X
#endif
#if defined MEWJAM_PUNCH_VEC_ANGLE_VEL
#error `MEWJAM_PUNCH_VEC_ANGLE_VEL` is already defined _X
#endif

#define MEWJAM_PUNCH_VEC_ANGLE "m_vecPunchAngle"
#define MEWJAM_PUNCH_VEC_ANGLE_VEL "m_vecPunchAngleVel"
