#if defined _mewjam_saytext_info_included_
#endinput
#endif
#define _mewjam_saytext_info_included_

#include <mewjam/version>

#define MEWJAM_SAYTEXT_NAME "Mewjam/SayText"
#define MEWJAM_SAYTEXT_NAME_LOWER "mewjam_saytext"
#define MEWJAM_SAYTEXT_AUTHOR "Mee;w"
#define MEWJAM_SAYTEXT_DESCRIPTION "Prints colored messages"
#define MEWJAM_SAYTEXT_URL "https://github.com/kty-trikz/plugins"

#define MEWJAM_SAYTEXT_VERSION_MAJOR 0
#define MEWJAM_SAYTEXT_VERSION_MINOR 1
#define MEWJAM_SAYTEXT_VERSION_PATCH 0

#define MEWJAM_SAYTEXT_VERSION_MAJOR_STRING "0"
#define MEWJAM_SAYTEXT_VERSION_MINOR_STRING "1"
#define MEWJAM_SAYTEXT_VERSION_PATCH_STRING "0"

#define MEWJAM_SAYTEXT_VERSION MEWJAM_VERSION_IMPL(MEWJAM_SAYTEXT_VERSION_MAJOR_STRING, MEWJAM_SAYTEXT_VERSION_MINOR_STRING, MEWJAM_SAYTEXT_VERSION_PATCH_STRING)
