#if defined _mewjam_equip_info_included_
#endinput
#endif
#define _mewjam_equip_info_included_

#include <mewjam/version>

#define MEWJAM_EQUIP_NAME "Mewjam/Equip"
#define MEWJAM_EQUIP_NAME_LOWER "mewjam_equip"
#define MEWJAM_EQUIP_AUTHOR "Mee;w"
#define MEWJAM_EQUIP_DESCRIPTION "Equipment of flashbangs"
#define MEWJAM_EQUIP_URL "https://github.com/kty-trikz/plugins"

#define MEWJAM_EQUIP_VERSION_MAJOR 0
#define MEWJAM_EQUIP_VERSION_MINOR 1
#define MEWJAM_EQUIP_VERSION_PATCH 1

#define MEWJAM_EQUIP_VERSION_MAJOR_STRING "0"
#define MEWJAM_EQUIP_VERSION_MINOR_STRING "1"
#define MEWJAM_EQUIP_VERSION_PATCH_STRING "1"

#define MEWJAM_EQUIP_VERSION MEWJAM_VERSION_IMPL(MEWJAM_EQUIP_VERSION_MAJOR_STRING, MEWJAM_EQUIP_VERSION_MINOR_STRING, MEWJAM_EQUIP_VERSION_PATCH_STRING)
