#if defined _mewjam_macro_info_included_
#endinput
#endif
#define _mewjam_macro_info_included_

#include <mewjam/version>

#define MEWJAM_MACRO_NAME "Mewjam/Macro"
#define MEWJAM_MACRO_NAME_LOWER "mewjam_macro"
#define MEWJAM_MACRO_AUTHOR "Mee;w"
#define MEWJAM_MACRO_DESCRIPTION "Flashbang throw macro"
#define MEWJAM_MACRO_URL "https://github.com/kty-trikz/plugins"

#define MEWJAM_MACRO_VERSION_MAJOR 0
#define MEWJAM_MACRO_VERSION_MINOR 1
#define MEWJAM_MACRO_VERSION_PATCH 2

#define MEWJAM_MACRO_VERSION_MAJOR_STRING "0"
#define MEWJAM_MACRO_VERSION_MINOR_STRING "1"
#define MEWJAM_MACRO_VERSION_PATCH_STRING "2"

#define MEWJAM_MACRO_VERSION MEWJAM_VERSION_IMPL(MEWJAM_MACRO_VERSION_MAJOR_STRING, MEWJAM_MACRO_VERSION_MINOR_STRING, MEWJAM_MACRO_VERSION_PATCH_STRING)
