#if defined _mewjam_respawn_info_included_
#endinput
#endif
#define _mewjam_respawn_info_included_

#include <mewjam/version>

#define MEWJAM_RESPAWN_NAME "Mewjam/Respawn"
#define MEWJAM_RESPAWN_NAME_LOWER "mewjam_respawn"
#define MEWJAM_RESPAWN_AUTHOR "Mee;w"
#define MEWJAM_RESPAWN_DESCRIPTION "Respawn player on their death"
#define MEWJAM_RESPAWN_URL "https://github.com/kty-trikz/plugins"

#define MEWJAM_RESPAWN_VERSION_MAJOR 0
#define MEWJAM_RESPAWN_VERSION_MINOR 1
#define MEWJAM_RESPAWN_VERSION_PATCH 0

#define MEWJAM_RESPAWN_VERSION_MAJOR_STRING "0"
#define MEWJAM_RESPAWN_VERSION_MINOR_STRING "1"
#define MEWJAM_RESPAWN_VERSION_PATCH_STRING "0"

#define MEWJAM_RESPAWN_VERSION MEWJAM_VERSION_IMPL(MEWJAM_RESPAWN_VERSION_MAJOR_STRING, MEWJAM_RESPAWN_VERSION_MINOR_STRING, MEWJAM_RESPAWN_VERSION_PATCH_STRING)
