#if defined _mewjam_noclip_info_included_
#endinput
#endif
#define _mewjam_noclip_info_included_

#include <mewjam/version>

#define MEWJAM_NOCLIP_NAME "Mewjam/Noclip"
#define MEWJAM_NOCLIP_NAME_LOWER "mewjam_noclip"
#define MEWJAM_NOCLIP_AUTHOR "Mee;w"
#define MEWJAM_NOCLIP_DESCRIPTION "Noclip for everyone"
#define MEWJAM_NOCLIP_URL "https://github.com/kty-trikz/plugins"

#define MEWJAM_NOCLIP_VERSION_MAJOR 0
#define MEWJAM_NOCLIP_VERSION_MINOR 2
#define MEWJAM_NOCLIP_VERSION_PATCH 0

#define MEWJAM_NOCLIP_VERSION_MAJOR_STRING "0"
#define MEWJAM_NOCLIP_VERSION_MINOR_STRING "2"
#define MEWJAM_NOCLIP_VERSION_PATCH_STRING "0"

#define MEWJAM_NOCLIP_VERSION MEWJAM_VERSION_IMPL(MEWJAM_NOCLIP_VERSION_MAJOR_STRING, MEWJAM_NOCLIP_VERSION_MINOR_STRING, MEWJAM_NOCLIP_VERSION_PATCH_STRING)
