#if defined _mewjam_classname_included_
#endinput
#endif
#define _mewjam_classname_included_

#define MEWJAM_CLASSNAME_WEAPON_FLASHBANG "weapon_flashbang"
#define MEWJAM_CLASSNAME_WEAPON_KNIFE "weapon_knife"
#define MEWJAM_CLASSNAME_WEAPON_SCOUT "weapon_scout"
#define MEWJAM_CLASSNAME_WEAPON_USP "weapon_usp"
#define MEWJAM_CLASSNAME_WEAPON_GLOCK "weapon_glock"
#define MEWJAM_CLASSNAME_PROJECTILE_FLASHBANG "flashbang_projectile"
