#if defined _mewjam_info_included_
#endinput
#endif
#define _mewjam_info_included_

#include <mewjam/version>

#define MEWJAM_NAME "Mewjam"
#define MEWJAM_NAME_LOWER "mewjam"
#define MEWJAM_AUTHOR "Mee;w"
#define MEWJAM_DESCRIPTION "Trikz"
#define MEWJAM_URL "https://github.com/kty-trikz/plugins"

#define MEWJAM_VERSION_MAJOR 0
#define MEWJAM_VERSION_MINOR 2
#define MEWJAM_VERSION_PATCH 2

#define MEWJAM_VERSION_MAJOR_STRING "0"
#define MEWJAM_VERSION_MINOR_STRING "2"
#define MEWJAM_VERSION_PATCH_STRING "2"

#define MEWJAM_VERSION MEWJAM_VERSION_IMPL(MEWJAM_VERSION_MAJOR_STRING, MEWJAM_VERSION_MINOR_STRING, MEWJAM_VERSION_PATCH_STRING)
