#if defined _mewjam_prop_included_
#endinput
#endif
#define _mewjam_prop_included_

#define MEWJAM_PROP_M_HOWNER "m_hOwner"
#define MEWJAM_PROP_M_HOWNERENTITY "m_hOwnerEntity"
#define MEWJAM_PROP_M_HTHROWER "m_hThrower"
#define MEWJAM_PROP_M_FLNEXTATTACK "m_flNextAttack"
#define MEWJAM_PROP_M_HACTIVEWEAPON "m_hActiveWeapon"
#define MEWJAM_PROP_M_NTICKBASE "m_nTickBase"
#define MEWJAM_PROP_M_FFLAGS "m_fFlags"
